export const GRID_CONFIG: GridConfig = {
    gridWidth: 10,
    gridHeight: 10,
    tileWidth: 64,
    tileHeight: 72,
    padding: 16,
    candies: [
        'cookie1',
        // 'cookie2',
        // 'croissant',
        // 'cupcake',
        'donut',
        'eclair',
        // 'macaroon',
        'pie',
        'poptart1',
        // 'poptart2',
        'starcookie1',
        // 'starcookie2',
    ],
    x: 0,
    y: 0,
    texture: 'ui',
    frame: 'candy-grid',
    leftWidth: 16,
    rightWidth: 16,
    topHeight: 16,
    bottomHeight: 16,
}
